name: WebdriverIO Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    
    - name: Install dependencies
      run: npm ci

    - name: Run WebdriverIO tests
      run: npx wdio wdio.conf.js
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: webdriverio-results
        path: ./test-results/
        retention-days: 30
